providers = ["node"]

[variables]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "22"

# Lemon AI required env vars
DOCKER_HOST_ADDR = "host.docker.internal"
ACTUAL_HOST_WORKSPACE_PATH = "/app/workspace"
STORAGE_PATH = "data/database.sqlite"
WORKSPACE_DIR = "workspace"
RUNTIME_TYPE = "local-docker"
ENABLE_KNOWLEDGE = "ON"

[phases.setup]
nixPkgs = ["nodejs_22", "npm"]
cmds = [
  "mkdir -p /app/data /app/workspace"
]

[phases.install]
depends_on = ["setup"]
cmds = [
  # Backend deps
  "npm install --production",
  # Frontend deps
  "cd frontend && npm install"
]

[phases.init]
depends_on = ["install"]
cmds = [
  # Initialize database tables
  "node src/models/sync.js"
]

[start]
cmd = "npm run start & cd frontend && npm run dev"
