[phases.setup]
nixPkgs = ['nodejs_22']
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']

[phases.install]
cmds = [
    'mkdir -p /app/data /app/workspace',
    'npm install --production',
    'cd frontend && npm install'
]

[start]
cmd = 'node src/models/sync.js && npm run start & cd frontend && npm run dev'
